name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/ui-kit/images/visa-logo.png
    - assets/ui-kit/images/status-bar.png
    - assets/ui-kit/images/visa-logo-qJC.png
    - assets/ui-kit/images/arrowicon.png
    - assets/ui-kit/images/backicon.png
    - assets/ui-kit/images/helpicon.png
    - assets/ui-kit/images/rectangle.png
    - assets/ui-kit/images/sendicon.png
    - assets/ui-kit/images/sendicon-VaL.png
    - assets/ui-kit/images/dots.png
    - assets/thumb-/images/image-6.png
    - assets/ui-kit/images/notifications-icon.png
    - assets/ui-kit/images/sendicon-enx.png
    - assets/ui-kit/images/cardicon.png
    - assets/ui-kit/images/auto-group-5vt4.png
    - assets/ui-kit/images/status-bar-WV2.png
    - assets/ui-kit/images/editicon.png
    - assets/ui-kit/images/removeillustration.png
    - assets/ui-kit/images/sendicon-EjE.png
    - assets/ui-kit/images/logouticon.png
    - assets/ui-kit/images/sentillustration.png
    - assets/ui-kit/images/profile-picture.png
    - assets/ui-kit/images/visa-logo-dCg.png
    - assets/ui-kit/images/backicon-8Yk.png
    - assets/ui-kit/images/homeicon.png
    - assets/ui-kit/images/contactsicon.png
    - assets/ui-kit/images/sendicon-8rg.png
    - assets/thumb-/images/figma.png
    - assets/ui-kit/images/auto-group-k6xe.png
    - assets/ui-kit/images/sentillustration-5M6.png
    - assets/ui-kit/images/profile-picture-UKE.png
    - assets/ui-kit/images/status-bar-bmn.png
    - assets/ui-kit/images/sendicon-oik.png
    - assets/ui-kit/images/addicon.png
    - assets/ui-kit/images/backicon-WBE.png
    - assets/ui-kit/images/profileicon.png
    - assets/ui-kit/images/sendicon-m1E.png
    - assets/ui-kit/images/request-button.png
    - assets/ui-kit/images/backicon-ewW.png
    - assets/ui-kit/images/profile-picture-s3a.png
    - assets/ui-kit/images/status-bar-fWU.png
    - assets/ui-kit/images/request-button-WX6.png
    - assets/ui-kit/images/backicon-7DN.png
    - assets/ui-kit/images/usericon.png
    - assets/ui-kit/images/auto-group-bshw.png
    - assets/ui-kit/images/send-button.png
    - assets/ui-kit/images/rectangle-RRW.png
    - assets/ui-kit/images/visa-logo-LKW.png
    - assets/ui-kit/images/notifications-icon-fCY.png
    - assets/ui-kit/images/arrowsicon.png
    - assets/ui-kit/images/rectangle-yDE.png
    - assets/thumb-/images/image-01.png
    - assets/thumb-/images/image-02.png
    - assets/ui-kit/images/backicon-KpY.png
    - assets/ui-kit/images/send-button-Bbr.png
    - assets/ui-kit/images/status-bar-X9v.png
    - assets/ui-kit/images/profile-picture-sja.png
    - assets/ui-kit/images/languageicon.png
    - assets/ui-kit/images/settingsicon.png
    - assets/ui-kit/images/arrowicon-pA8.png
    - assets/ui-kit/images/status-bar-NBe.png
    - assets/ui-kit/images/visa-logo-8Ri.png
    - assets/ui-kit/images/backicon-6NY.png
    - assets/ui-kit/images/visa-logo-ZoA.png
    - assets/ui-kit/images/sendicon-Vgp.png
    - assets/ui-kit/images/status-bar-EPW.png
    - assets/ui-kit/images/backicon-BJk.png
    - assets/ui-kit/images/profile-picture-8zg.png
    - assets/ui-kit/images/requesticon.png
    - assets/ui-kit/images/send-button-utx.png
    - assets/ui-kit/images/sendicon-EjW.png
    - assets/ui-kit/images/arrowicon-nm2.png
    - assets/ui-kit/images/profile-picture-Z16.png
    - assets/ui-kit/images/backicon-28t.png
    - assets/ui-kit/images/status-bar-xYL.png
    - assets/ui-kit/images/remove-button.png
    - assets/ui-kit/images/locationicon.png
    - assets/ui-kit/images/requesticon-GDa.png
    - assets/ui-kit/images/callicon.png
    - assets/ui-kit/images/profile-picture-9oA.png
    - assets/ui-kit/images/status-bar-D2L.png
    - assets/ui-kit/images/addicon-9Rn.png
    - assets/ui-kit/images/send-button-Uyr.png
    - assets/thumb-/images/image-04.png
    - assets/ui-kit/images/request-button-Zxg.png
    - assets/ui-kit/images/profile-picture-jEt.png
    - assets/thumb-/images/image-05.png
    - assets/ui-kit/images/request-button-7x8.png
    - assets/ui-kit/images/status-bar-CUL.png
    - assets/ui-kit/images/usericon-E9S.png
    - assets/ui-kit/images/sendicon-g9r.png
    - assets/ui-kit/images/rectangle-PiU.png
    - assets/ui-kit/images/auto-group-xxgl.png
    - assets/ui-kit/images/rectangle-jw2.png
    - assets/ui-kit/images/auto-group-r2w6.png
    - assets/ui-kit/images/backicon-Q7v.png
    - assets/ui-kit/images/request-button-37a.png
    - assets/ui-kit/images/sendicon-avg.png
    - assets/ui-kit/images/remove-button-uYx.png
    - assets/ui-kit/images/status-bar-Cfn.png
    - assets/ui-kit/images/usericon-GZa.png
    - assets/thumb-/images/logo.png
    - assets/ui-kit/images/profile-picture-U2Y.png
    - assets/ui-kit/images/rectangle-3He.png
    - assets/ui-kit/images/status-bar-X6L.png
    - assets/ui-kit/images/dots-gWQ.png
    - assets/ui-kit/images/arrowicon-wt8.png
    - assets/thumb-/images/image-03.png
    - assets/ui-kit/images/backicon-UFN.png
    - assets/ui-kit/images/auto-group-6vgx.png
    - assets/ui-kit/images/contactsicon-BhW.png
    - assets/ui-kit/images/searchicon.png
    - assets/ui-kit/images/request-button-hAU.png
    - assets/ui-kit/images/profile-picture-RRW.png
    - assets/ui-kit/images/send-button-17A.png
    - assets/ui-kit/images/arrowsicon-HcQ.png
    - assets/ui-kit/images/profile-picture-mE4.png
    - assets/ui-kit/images/homeicon-pWQ.png
    - assets/ui-kit/images/status-bar-p2Q.png
    - assets/ui-kit/images/request-button-YUC.png
    - assets/ui-kit/images/request-button-c6g.png
    - assets/ui-kit/images/contactsicon-EBE.png
    - assets/ui-kit/images/addicon-BcG.png
    - assets/ui-kit/images/send-button-xxk.png
    - assets/ui-kit/images/searchicon-6oN.png
    - assets/ui-kit/images/status-bar-hgg.png
    - assets/ui-kit/images/send-button-byW.png
    - assets/ui-kit/images/homeicon-A12.png
    - assets/ui-kit/images/send-button-yQ8.png
    - assets/ui-kit/images/list.png
    - assets/ui-kit/images/arrowsicon-Ghr.png
    - assets/ui-kit/images/usericon-bQg.png
    - assets/ui-kit/images/profile-picture-boJ.png
    - assets/ui-kit/images/contactsicon-SMr.png
    - assets/ui-kit/images/path.png
    - assets/ui-kit/images/usericon-ptL.png
    - assets/ui-kit/images/profile-picture-CtC.png
    - assets/ui-kit/images/oval.png
    - assets/ui-kit/images/status-bar-yiU.png
    - assets/ui-kit/images/arrowsicon-kSg.png
    - assets/ui-kit/images/sendicon-65A.png
    - assets/ui-kit/images/notifications-icon-M5N.png
    - assets/ui-kit/images/profile-picture-kGc.png
    - assets/ui-kit/images/profile-picture-Gc4.png
    - assets/ui-kit/images/profile-picture-Eck.png
    - assets/ui-kit/images/profile-picture-DCQ.png
    - assets/ui-kit/images/profile-picture-2Fn.png
    - assets/ui-kit/images/profile-picture-hWC.png
    - assets/ui-kit/images/profile-picture-fTJ.png
    - assets/ui-kit/images/requesticon-g12.png
    - assets/ui-kit/images/sendicon-hRE.png
    - assets/ui-kit/images/homeicon-tui.png
    - assets/ui-kit/images/requesticon-5t8.png
    - assets/ui-kit/images/path-USp.png
    - assets/ui-kit/images/profile-picture-Mpg.png
    - assets/ui-kit/images/profile-picture-YAx.png
    - assets/ui-kit/images/notifications-icon-NyJ.png
    - assets/ui-kit/images/contactsicon-bNc.png
    - assets/ui-kit/images/profile-picture-eSg.png
    - assets/ui-kit/images/profile-picture-TwJ.png
    - assets/ui-kit/images/profile-picture-3Cg.png
    - assets/ui-kit/images/profile-picture-PYY.png
    - assets/ui-kit/images/profile-picture-xWg.png
    - assets/ui-kit/images/profile-picture-8Eg.png
    - assets/ui-kit/images/background.png
    - assets/ui-kit/images/status-bar-geY.png
    - assets/ui-kit/images/arrowsicon-j3a.png
    - assets/ui-kit/images/sendicon-7mv.png
    - assets/ui-kit/images/status-bar-ScU.png
    - assets/ui-kit/images/viewicon.png
    - assets/ui-kit/images/viewicon-ZUQ.png
    - assets/ui-kit/images/profile-picture-tex.png
    - assets/ui-kit/images/background-cDa.png
    - assets/ui-kit/images/requesticon-uj2.png
    - assets/ui-kit/images/background-7PA.png
    - assets/ui-kit/images/viewicon-2yA.png
    - assets/ui-kit/images/status-bar-7B2.png
    - assets/ui-kit/images/sendicon-DqN.png
    - assets/ui-kit/images/status-bar-zmJ.png
    - assets/ui-kit/images/requesticon-XWL.png
    - assets/ui-kit/images/homeicon-WbN.png
    - assets/ui-kit/images/requesticon-8GU.png
    - assets/ui-kit/images/status-bar-AsN.png
    - assets/ui-kit/images/auto-group-wohe.png
    - assets/ui-kit/images/logo-12C.png
    - assets/ui-kit/images/status-bar-eyi.png
    - assets/ui-kit/images/wallet-rafiki.png
    - assets/ui-kit/images/usericon-aya.png
    - assets/ui-kit/images/viewicon-31v.png
    - assets/ui-kit/images/status-bar-kQ4.png
    - assets/ui-kit/images/logo-DWL.png
    - assets/ui-kit/images/status-bar-GBW.png
    - assets/ui-kit/images/illustration.png
    - assets/ui-kit/images/status-bar-Ss6.png
    - assets/ui-kit/images/illustration-oic.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
